layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 6
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: jonas-zengerle
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Kubernetes
    web_url: https://github.com/topics/kubernetes
    image_url: https://raw.githubusercontent.com/github/explore/32e4800d11d2ecab0d13aa5e729c9e05c52f571e/topics/kubernetes/kubernetes.png

  - name: Docker
    web_url: https://github.com/topics/docker
    image_url: https://raw.githubusercontent.com/github/explore/32e4800d11d2ecab0d13aa5e729c9e05c52f571e/topics/docker/docker.png

  - name: Go(Lang)
    web_url: https://github.com/topics/go
    image_url: https://raw.githubusercontent.com/github/explore/32e4800d11d2ecab0d13aa5e729c9e05c52f571e/topics/go/go.png

  - name: Linux
    web_url: https://github.com/topics/linux
    image_url: https://raw.githubusercontent.com/github/explore/32e4800d11d2ecab0d13aa5e729c9e05c52f571e/topics/linux/linux.png

  - name: Security
    web_url: https://github.com/topics/security

  - name: DevSecOps
    web_url: https://github.com/topics/devsecops

  - name: Amazon Web Services
    web_url: https://github.com/topics/aws
    image_url: https://raw.githubusercontent.com/github/explore/32e4800d11d2ecab0d13aa5e729c9e05c52f571e/topics/aws/aws.png

  - name: Azure
    web_url: https://github.com/topics/azure
    image_url: https://raw.githubusercontent.com/github/explore/32e4800d11d2ecab0d13aa5e729c9e05c52f571e/topics/azure/azure.png

  - name: Google Cloud Platform
    web_url: https://github.com/topics/gcp

  - name: Project Management
    web_url: https://github.com/topics/project-management

  - name: Deep Learning
    web_url: https://github.com/topics/deep-learning

  - name: Enterprise Software
    web_url: https://github.com/topics/enterprise-software
